Start testing: Jan 17 18:30 CET
----------------------------------------------------------
2/56 Testing: 1D.test_runner.B2_BeG_017
2/56 Test: 1D.test_runner.B2_BeG_017
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/1D/B2_BeG_017
"1D.test_runner.B2_BeG_017" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 113, in compare_tab_files
    assert (data_ok[field] == data_new[field]).all(),  \
  File "/usr/lib/python2.7/dist-packages/pandas/core/ops.py", line 812, in wrapper
    raise ValueError(msg)
ValueError: Can only compare identically-labeled Series objects
<end of output>
Test time =   0.72 sec
----------------------------------------------------------
Test Failed.
"1D.test_runner.B2_BeG_017" end time: Jan 17 18:30 CET
"1D.test_runner.B2_BeG_017" time elapsed: 00:00:00
----------------------------------------------------------

4/56 Testing: 1D.test_runner.Bro
4/56 Test: 1D.test_runner.Bro
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/1D/Bro
"1D.test_runner.Bro" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 114, in compare_tab_files
    "Field '%s' of files %s and %s differs!" % (field, fpath_ok, fpath_new)
AssertionError: Field '150.000000 ' of files /home/grz/exact-lab/geotop_project/geotop/tests/1D/Bro/output-tabs-METEOIO-OFF/water_press0001.txt and /home/grz/exact-lab/geotop_project/geotop/tests/1D/Bro/output-tabs/water_press0001.txt differs!
<end of output>
Test time =   0.77 sec
----------------------------------------------------------
Test Failed.
"1D.test_runner.Bro" end time: Jan 17 18:30 CET
"1D.test_runner.Bro" time elapsed: 00:00:00
----------------------------------------------------------

6/56 Testing: 1D.test_runner.Calabria
6/56 Test: 1D.test_runner.Calabria
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/1D/Calabria
"1D.test_runner.Calabria" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 113, in compare_tab_files
    assert (data_ok[field] == data_new[field]).all(),  \
  File "/usr/lib/python2.7/dist-packages/pandas/core/ops.py", line 812, in wrapper
    raise ValueError(msg)
ValueError: Can only compare identically-labeled Series objects
<end of output>
Test time =   0.42 sec
----------------------------------------------------------
Test Failed.
"1D.test_runner.Calabria" end time: Jan 17 18:30 CET
"1D.test_runner.Calabria" time elapsed: 00:00:00
----------------------------------------------------------

8/56 Testing: 1D.test_runner.ColdelaPorte
8/56 Test: 1D.test_runner.ColdelaPorte
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/1D/ColdelaPorte
"1D.test_runner.ColdelaPorte" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 110, in compare_tab_files
    deltas[field], abs(data_ok[field] - data_new[field]).max())
AssertionError: Field '100.000000' in file /home/grz/exact-lab/geotop_project/geotop/tests/1D/ColdelaPorte/output-tabs/ground0001.txt is too different: 20 rows differ more than 0.100000 from the correct ones (maxdiff=0.770887).
<end of output>
Test time =   0.41 sec
----------------------------------------------------------
Test Failed.
"1D.test_runner.ColdelaPorte" end time: Jan 17 18:30 CET
"1D.test_runner.ColdelaPorte" time elapsed: 00:00:00
----------------------------------------------------------

10/56 Testing: 1D.test_runner.CostantMeteo
10/56 Test: 1D.test_runner.CostantMeteo
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/1D/CostantMeteo
"1D.test_runner.CostantMeteo" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 114, in compare_tab_files
    "Field '%s' of files %s and %s differs!" % (field, fpath_ok, fpath_new)
AssertionError: Field '5.000000 ' of files /home/grz/exact-lab/geotop_project/geotop/tests/1D/CostantMeteo/output-tabs-METEOIO-OFF/T0001.txt and /home/grz/exact-lab/geotop_project/geotop/tests/1D/CostantMeteo/output-tabs/T0001.txt differs!
<end of output>
Test time =   0.45 sec
----------------------------------------------------------
Test Failed.
"1D.test_runner.CostantMeteo" end time: Jan 17 18:30 CET
"1D.test_runner.CostantMeteo" time elapsed: 00:00:00
----------------------------------------------------------

12/56 Testing: 1D.test_runner.Jungfraujoch
12/56 Test: 1D.test_runner.Jungfraujoch
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/1D/Jungfraujoch
"1D.test_runner.Jungfraujoch" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 114, in compare_tab_files
    "Field '%s' of files %s and %s differs!" % (field, fpath_ok, fpath_new)
AssertionError: Field '100.000000 ' of files /home/grz/exact-lab/geotop_project/geotop/tests/1D/Jungfraujoch/output-tabs-METEOIO-OFF/soil0032.txt and /home/grz/exact-lab/geotop_project/geotop/tests/1D/Jungfraujoch/output-tabs/soil0032.txt differs!
<end of output>
Test time =   0.41 sec
----------------------------------------------------------
Test Failed.
"1D.test_runner.Jungfraujoch" end time: Jan 17 18:30 CET
"1D.test_runner.Jungfraujoch" time elapsed: 00:00:00
----------------------------------------------------------

14/56 Testing: 1D.test_runner.PureDrainage
14/56 Test: 1D.test_runner.PureDrainage
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/1D/PureDrainage
"1D.test_runner.PureDrainage" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
<end of output>
Test time =   0.39 sec
----------------------------------------------------------
Test Passed.
"1D.test_runner.PureDrainage" end time: Jan 17 18:30 CET
"1D.test_runner.PureDrainage" time elapsed: 00:00:00
----------------------------------------------------------

16/56 Testing: 1D.test_runner.PureDrainageFaked
16/56 Test: 1D.test_runner.PureDrainageFaked
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/1D/PureDrainageFaked
"1D.test_runner.PureDrainageFaked" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
<end of output>
Test time =   0.39 sec
----------------------------------------------------------
Test Passed.
"1D.test_runner.PureDrainageFaked" end time: Jan 17 18:30 CET
"1D.test_runner.PureDrainageFaked" time elapsed: 00:00:00
----------------------------------------------------------

18/56 Testing: 1D.test_runner.PureDrainageRainy
18/56 Test: 1D.test_runner.PureDrainageRainy
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/1D/PureDrainageRainy
"1D.test_runner.PureDrainageRainy" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
<end of output>
Test time =   0.40 sec
----------------------------------------------------------
Test Passed.
"1D.test_runner.PureDrainageRainy" end time: Jan 17 18:30 CET
"1D.test_runner.PureDrainageRainy" time elapsed: 00:00:00
----------------------------------------------------------

20/56 Testing: 3D.test_runner.Borden05m
20/56 Test: 3D.test_runner.Borden05m
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/Borden05m
"3D.test_runner.Borden05m" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
<end of output>
Test time =   0.48 sec
----------------------------------------------------------
Test Passed.
"3D.test_runner.Borden05m" end time: Jan 17 18:30 CET
"3D.test_runner.Borden05m" time elapsed: 00:00:00
----------------------------------------------------------

22/56 Testing: 3D.test_runner.Mazia
22/56 Test: 3D.test_runner.Mazia
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/Mazia
"3D.test_runner.Mazia" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 114, in compare_tab_files
    "Field '%s' of files %s and %s differs!" % (field, fpath_ok, fpath_new)
AssertionError: Field '5.000000 ' of files /home/grz/exact-lab/geotop_project/geotop/tests/3D/Mazia/output-tabs-METEOIO-OFF/soiltemp0008.txt and /home/grz/exact-lab/geotop_project/geotop/tests/3D/Mazia/output-tabs/soiltemp0008.txt differs!
<end of output>
Test time =   0.41 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.Mazia" end time: Jan 17 18:30 CET
"3D.test_runner.Mazia" time elapsed: 00:00:00
----------------------------------------------------------

24/56 Testing: 3D.test_runner.PSQL_test
24/56 Test: 3D.test_runner.PSQL_test
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/PSQL_test
"3D.test_runner.PSQL_test" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 237, in test_generator
    self._test_template( actual_dir, maps )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 223, in _test_template
    assert_is_file(fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 81, in assert_is_file
    assert os.path.isfile(fname), msg or "%s is not a file" % fname
AssertionError: /home/grz/exact-lab/geotop_project/geotop/tests/3D/PSQL_test/output-tabs/HNN0049.asc is not a file
<end of output>
Test time =   0.39 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.PSQL_test" end time: Jan 17 18:30 CET
"3D.test_runner.PSQL_test" time elapsed: 00:00:00
----------------------------------------------------------

26/56 Testing: 3D.test_runner.WG1_2.0_001
26/56 Test: 3D.test_runner.WG1_2.0_001
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/WG1_2.0_001
"3D.test_runner.WG1_2.0_001" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
<end of output>
Test time =   0.39 sec
----------------------------------------------------------
Test Passed.
"3D.test_runner.WG1_2.0_001" end time: Jan 17 18:30 CET
"3D.test_runner.WG1_2.0_001" time elapsed: 00:00:00
----------------------------------------------------------

28/56 Testing: 3D.test_runner.bonn_1
28/56 Test: 3D.test_runner.bonn_1
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/bonn_1
"3D.test_runner.bonn_1" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 237, in test_generator
    self._test_template( actual_dir, maps )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 223, in _test_template
    assert_is_file(fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 81, in assert_is_file
    assert os.path.isfile(fname), msg or "%s is not a file" % fname
AssertionError: /home/grz/exact-lab/geotop_project/geotop/tests/3D/bonn_1/output-tabs/PwL0005N0002.asc is not a file
<end of output>
Test time =   0.40 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.bonn_1" end time: Jan 17 18:30 CET
"3D.test_runner.bonn_1" time elapsed: 00:00:00
----------------------------------------------------------

30/56 Testing: 3D.test_runner.bonn_2
30/56 Test: 3D.test_runner.bonn_2
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/bonn_2
"3D.test_runner.bonn_2" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 179, in compare_files
    return compare_files_exactly(fpath_ok, fpath_new, None)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 90, in compare_files_exactly
    assert filecmp.cmp(fpath_ok, fpath_new), "File %s and %s differ!" % (fpath_ok, fpath_new)
AssertionError: File /home/grz/exact-lab/geotop_project/geotop/tests/3D/bonn_2/output-tabs-METEOIO-OFF/basin.txt and /home/grz/exact-lab/geotop_project/geotop/tests/3D/bonn_2/output-tabs/basin.txt differ!
<end of output>
Test time =   0.40 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.bonn_2" end time: Jan 17 18:30 CET
"3D.test_runner.bonn_2" time elapsed: 00:00:00
----------------------------------------------------------

32/56 Testing: 3D.test_runner.example
32/56 Test: 3D.test_runner.example
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/example
"3D.test_runner.example" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 110, in compare_tab_files
    deltas[field], abs(data_ok[field] - data_new[field]).max())
AssertionError: Field 'Tsurface[C]' in file /home/grz/exact-lab/geotop_project/geotop/tests/3D/example/output-tabs/point0001.txt is too different: 3 rows differ more than 3.000000 from the correct ones (maxdiff=15.250714).
<end of output>
Test time =   0.41 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.example" end time: Jan 17 18:30 CET
"3D.test_runner.example" time elapsed: 00:00:00
----------------------------------------------------------

34/56 Testing: 3D.test_runner.hillslope01
34/56 Test: 3D.test_runner.hillslope01
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/hillslope01
"3D.test_runner.hillslope01" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
<end of output>
Test time =   1.08 sec
----------------------------------------------------------
Test Passed.
"3D.test_runner.hillslope01" end time: Jan 17 18:30 CET
"3D.test_runner.hillslope01" time elapsed: 00:00:01
----------------------------------------------------------

36/56 Testing: 3D.test_runner.hillslope02_superslab
36/56 Test: 3D.test_runner.hillslope02_superslab
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/hillslope02_superslab
"3D.test_runner.hillslope02_superslab" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
<end of output>
Test time =   1.08 sec
----------------------------------------------------------
Test Passed.
"3D.test_runner.hillslope02_superslab" end time: Jan 17 18:30 CET
"3D.test_runner.hillslope02_superslab" time elapsed: 00:00:01
----------------------------------------------------------

38/56 Testing: 3D.test_runner.no_reflection
38/56 Test: 3D.test_runner.no_reflection
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/no_reflection
"3D.test_runner.no_reflection" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 237, in test_generator
    self._test_template( actual_dir, maps )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 223, in _test_template
    assert_is_file(fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 81, in assert_is_file
    assert os.path.isfile(fname), msg or "%s is not a file" % fname
AssertionError: /home/grz/exact-lab/geotop_project/geotop/tests/3D/no_reflection/output-tabs/TL0003N0090.asc is not a file
<end of output>
Test time =   0.41 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.no_reflection" end time: Jan 17 18:30 CET
"3D.test_runner.no_reflection" time elapsed: 00:00:00
----------------------------------------------------------

40/56 Testing: 3D.test_runner.panola
40/56 Test: 3D.test_runner.panola
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/panola
"3D.test_runner.panola" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 237, in test_generator
    self._test_template( actual_dir, maps )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 223, in _test_template
    assert_is_file(fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 81, in assert_is_file
    assert os.path.isfile(fname), msg or "%s is not a file" % fname
AssertionError: /home/grz/exact-lab/geotop_project/geotop/tests/3D/panola/output-tabs/psiliqL0004N0001.asc is not a file
<end of output>
Test time =   0.48 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.panola" end time: Jan 17 18:30 CET
"3D.test_runner.panola" time elapsed: 00:00:00
----------------------------------------------------------

42/56 Testing: 3D.test_runner.panola_25pixel
42/56 Test: 3D.test_runner.panola_25pixel
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/panola_25pixel
"3D.test_runner.panola_25pixel" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 237, in test_generator
    self._test_template( actual_dir, maps )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 223, in _test_template
    assert_is_file(fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 81, in assert_is_file
    assert os.path.isfile(fname), msg or "%s is not a file" % fname
AssertionError: /home/grz/exact-lab/geotop_project/geotop/tests/3D/panola_25pixel/output-tabs/psiliqL0004N0001.asc is not a file
<end of output>
Test time =   0.49 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.panola_25pixel" end time: Jan 17 18:30 CET
"3D.test_runner.panola_25pixel" time elapsed: 00:00:00
----------------------------------------------------------

44/56 Testing: 3D.test_runner.panola_25pixel_nobed
44/56 Test: 3D.test_runner.panola_25pixel_nobed
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/panola_25pixel_nobed
"3D.test_runner.panola_25pixel_nobed" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 237, in test_generator
    self._test_template( actual_dir, maps )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 223, in _test_template
    assert_is_file(fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 81, in assert_is_file
    assert os.path.isfile(fname), msg or "%s is not a file" % fname
AssertionError: /home/grz/exact-lab/geotop_project/geotop/tests/3D/panola_25pixel_nobed/output-tabs/psiliqL0004N0001.asc is not a file
<end of output>
Test time =   0.49 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.panola_25pixel_nobed" end time: Jan 17 18:30 CET
"3D.test_runner.panola_25pixel_nobed" time elapsed: 00:00:00
----------------------------------------------------------

46/56 Testing: 3D.test_runner.prealpiC
46/56 Test: 3D.test_runner.prealpiC
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/prealpiC
"3D.test_runner.prealpiC" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
<end of output>
Test time =   0.51 sec
----------------------------------------------------------
Test Passed.
"3D.test_runner.prealpiC" end time: Jan 17 18:30 CET
"3D.test_runner.prealpiC" time elapsed: 00:00:00
----------------------------------------------------------

48/56 Testing: 3D.test_runner.rendena
48/56 Test: 3D.test_runner.rendena
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/rendena
"3D.test_runner.rendena" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 237, in test_generator
    self._test_template( actual_dir, maps )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 223, in _test_template
    assert_is_file(fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 81, in assert_is_file
    assert os.path.isfile(fname), msg or "%s is not a file" % fname
AssertionError: /home/grz/exact-lab/geotop_project/geotop/tests/3D/rendena/output-tabs/SWEDENSITYN0001.asc is not a file
<end of output>
Test time =   0.40 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.rendena" end time: Jan 17 18:30 CET
"3D.test_runner.rendena" time elapsed: 00:00:00
----------------------------------------------------------

50/56 Testing: 3D.test_runner.small_example
50/56 Test: 3D.test_runner.small_example
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/small_example
"3D.test_runner.small_example" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 114, in compare_tab_files
    "Field '%s' of files %s and %s differs!" % (field, fpath_ok, fpath_new)
AssertionError: Field 'L1' of files /home/grz/exact-lab/geotop_project/geotop/tests/3D/small_example/output-tabs-METEOIO-OFF/snowtemp0002.txt and /home/grz/exact-lab/geotop_project/geotop/tests/3D/small_example/output-tabs/snowtemp0002.txt differs!
<end of output>
Test time =   0.40 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.small_example" end time: Jan 17 18:30 CET
"3D.test_runner.small_example" time elapsed: 00:00:00
----------------------------------------------------------

52/56 Testing: 3D.test_runner.small_example-channel
52/56 Test: 3D.test_runner.small_example-channel
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/small_example-channel
"3D.test_runner.small_example-channel" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 114, in compare_tab_files
    "Field '%s' of files %s and %s differs!" % (field, fpath_ok, fpath_new)
AssertionError: Field 'L1' of files /home/grz/exact-lab/geotop_project/geotop/tests/3D/small_example-channel/output-tabs-METEOIO-OFF/snowliq0001.txt and /home/grz/exact-lab/geotop_project/geotop/tests/3D/small_example-channel/output-tabs/snowliq0001.txt differs!
<end of output>
Test time =   0.41 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.small_example-channel" end time: Jan 17 18:30 CET
"3D.test_runner.small_example-channel" time elapsed: 00:00:00
----------------------------------------------------------

54/56 Testing: 3D.test_runner.small_example-onlyEnergy
54/56 Test: 3D.test_runner.small_example-onlyEnergy
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/small_example-onlyEnergy
"3D.test_runner.small_example-onlyEnergy" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 244, in <module>
    t.test_generator()
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 233, in test_generator
    self._test_template( actual_dir, tabs_dir )
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 225, in _test_template
    self.compare_files(fpath_ok, fpath_new)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 178, in compare_files
    return func(fpath_ok, fpath_new, delta)
  File "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py", line 110, in compare_tab_files
    deltas[field], abs(data_ok[field] - data_new[field]).max())
AssertionError: Field 'Tsurface[C]' in file /home/grz/exact-lab/geotop_project/geotop/tests/3D/small_example-onlyEnergy/output-tabs/point0001.txt is too different: 18 rows differ more than 3.000000 from the correct ones (maxdiff=11.317232).
<end of output>
Test time =   0.42 sec
----------------------------------------------------------
Test Failed.
"3D.test_runner.small_example-onlyEnergy" end time: Jan 17 18:30 CET
"3D.test_runner.small_example-onlyEnergy" time elapsed: 00:00:00
----------------------------------------------------------

56/56 Testing: 3D.test_runner.snow_dstr_SENSITIVITY
56/56 Test: 3D.test_runner.snow_dstr_SENSITIVITY
Command: "/usr/bin/python" "/home/grz/exact-lab/geotop_project/geotop/tests/test_runner.py"
Directory: /home/grz/exact-lab/geotop_project/geotop/tests/3D/snow_dstr_SENSITIVITY
"3D.test_runner.snow_dstr_SENSITIVITY" start time: Jan 17 18:30 CET
Output:
----------------------------------------------------------
<end of output>
Test time =   2.40 sec
----------------------------------------------------------
Test Passed.
"3D.test_runner.snow_dstr_SENSITIVITY" end time: Jan 17 18:30 CET
"3D.test_runner.snow_dstr_SENSITIVITY" time elapsed: 00:00:02
----------------------------------------------------------

End testing: Jan 17 18:30 CET
